version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: school_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_db
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school_password
    ports:
      - "3306:3306"
    volumes:
      - school_db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: school_db_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  school_db_data:
