version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: school_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_db
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school_password
    ports:
      - "3308:3306"
    volumes:
      - school_db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: school_db_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: school_user
      DB_PASSWORD: school_password
      DB_DATABASE: school_db
    depends_on:
      - mariadb

volumes:
  school_db_data:
